#!/usr/bin/env bash
#===================================================================================
# LESSON 3: Linux Directory Structure
#===================================================================================
# Linux has a STANDARD directory layout. Unlike Windows (C:, D:), everything
# starts from ONE root: /
#
# Think of it like a tree:
#         /           <-- The ROOT (top of everything)
#        /|\
#       / | \
#      /  |  \
#   bin  home  etc
#        /\
#       /  \
#    diego  jane
#
# Here's what the main directories are for:
#===================================================================================

set -euxo pipefail

echo "=========================================="
echo "LESSON 3: Linux Directory Structure"
echo "=========================================="
echo ""

# Debug: Show the root
echo "[DEBUG] The root directory / contains:"
ls /
echo ""

# Debug: Explain each directory
echo "[DEBUG] What each directory is for:"
echo ""

echo "/bin  - Essential BINaries (commands everyone needs)"
echo "       Examples: ls, cp, mv, cat, echo"
ls /bin | head -5
echo "       ... and $(ls /bin | wc -l) more commands"
echo ""

echo "/boot - Files needed to BOOT (start) the system"
echo "       Kernel, initramfs, bootloader config"
ls /boot 2>/dev/null | head -3 || echo "       (may need permissions to view)"
echo ""

echo "/dev  - DEVice files (how Linux talks to hardware)"
echo "       /dev/null = black hole (discard output)"
echo "       /dev/sda = your hard drive"
ls /dev | head -5
echo "       ... and $(ls /dev | wc -l) device files"
echo ""

echo "/etc  - Configuration files (system settings)"
echo "       NOT 'etcetera' - historically 'editable text configuration'"
echo "       /etc/passwd = user info"
echo "       /etc/hosts  = network names"
ls /etc | head -5
echo "       ... and $(ls /etc | wc -l) config files"
echo ""

echo "/home - User HOME directories"
echo "       Each user gets their own space"
echo "       Your stuff goes in /home/YOURNAME"
ls /home
echo ""

echo "/var  - VARiable data (things that change/grow)"
echo "       Logs: /var/log"
echo "       Caches: /var/cache"
echo "       Temp files: /var/tmp"
ls /var
echo ""

echo "/tmp  - Temporary files (deleted on reboot usually)"
echo "       Good for short-lived experiments"
ls /tmp | head -5
echo ""

echo "/usr  - USR (Unix System Resources)"
echo "       User programs and data"
echo "       /usr/bin = most commands"
echo "       /usr/lib = libraries"
ls /usr
echo ""

echo "/proc - PROCess information (virtual filesystem)"
echo "       Not real files! Generated by kernel on-the-fly"
echo "       /proc/cpuinfo = CPU info"
echo "       /proc/meminfo = Memory info"
echo "       /proc/\$\$ = info about this script's process"
cat /proc/cpuinfo | head -5
echo ""

echo "/sys  - SYStem info (like /proc but for hardware/drivers)"
ls /sys | head -5
echo ""

# Debug: Visual tree
echo "[DEBUG] Visual tree of Linux:"
cat << 'TREE'
/
├── bin/     -> Commands (ls, cp, cat)
├── boot/    -> Startup files
├── dev/     -> Devices (hardware)
├── etc/     -> Configuration
├── home/    -> User files
│   └── diego/
├── proc/    -> Process info (virtual)
├── sys/     -> System info (virtual)
├── tmp/     -> Temporary files
├── usr/     -> User programs
└── var/     -> Variable data (logs)
TREE

echo ""
echo "=========================================="
echo "KEY TAKEAWAYS:"
echo "1. Everything starts from / (root)"
echo "2. /bin, /usr = programs/commands"
echo "3. /etc = configuration"
echo "4. /home = your personal space"
echo "5. /dev = hardware devices"
echo "6. /proc, /sys = virtual (kernel-generated)"
echo "7. /var = logs and changing data"
echo "=========================================="
