"""
This script combines the data from the 20 excel files generated by the generate-data.py script. The data is combined into a single dataframe and saved to a new excel file.
"""


import pandas as pd
import os

# Create an empty dataframe to store the combined data
combined_data = pd.DataFrame()

# Loop through the 20 excel files
for i in range(0, 20):
    # Load the data from the excel file
    filepath = 'data/apples_week_{}.xlsx'.format(i+1)
    single_df = pd.read_excel(filepath)

    # Add a column to store the week number
    single_df['Week'] = i + 1

    # Append the data to the combined dataframe
    combined_data = pd.concat([combined_data, single_df])

# Save the combined data to a new excel file
combined_filepath = './combined_apples.xlsx'
combined_data.to_excel(combined_filepath, index=False)
print("Combined data saved to: ", combined_filepath)

# Display the combined data
print(combined_data)
